# Generated by Django 3.2.13 on 2022-05-12 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.CharField(blank=True, max_length=11, null=True, verbose_name='R$ Valor')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('recibo', models.BooleanField(default=False, verbose_name='Gerar Recibo?')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.CharField(blank=True, max_length=11, null=True, verbose_name='R$ Valor')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('recibo', models.BooleanField(default=False, verbose_name='Gerar Recibo?')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.paciente')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
