# Generated by Django 3.2.13 on 2022-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0002_recibo_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='recibo',
            field=models.BooleanField(default=False, verbose_name='Gerar recibo?'),
        ),
    ]
