# Generated by Django 3.2.13 on 2022-05-10 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, verbose_name='Nº CPF')),
                ('rg', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=100, verbose_name='Nº telefone celular')),
                ('endereco', models.CharField(max_length=100)),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('anamnesi', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
