# Generated by Django 3.2.13 on 2022-05-14 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('anamnesi', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='perfil')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
