# Generated by Django 3.2.13 on 2022-05-07 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20220505_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
