# Generated by Django 3.2.13 on 2022-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_consulta_procedimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='anamnesi',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='data_consulta',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='upload',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='custo_medio',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='R$ Valor'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='procedimeto',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
