# Generated by Django 3.2.13 on 2022-05-14 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20220514_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='custo_medio',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Custo Médio R$'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('procedimeto', models.CharField(blank=True, max_length=14, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='upload', verbose_name='Documentos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.paciente')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
