# Generated by Django 3.2.13 on 2022-05-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20220514_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='procedimeto',
            new_name='anamnesi',
        ),
    ]
